# Generated by Django 3.0.1 on 2020-01-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
