# Generated by Django 3.0.1 on 2020-01-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pizza_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
    ]
