# Generated by Django 3.0.1 on 2020-01-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.CartItem')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Topping')),
            ],
        ),
    ]
